apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-nfs-pv
  labels:
    volume: influxdb-nfs-pv
spec:
  capacity:
    storage: 512Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 172.29.156.100
    path: /srv/nfs/kube-monitoring/Influxdb
