apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc-lb
  namespace: kube-monitoring
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
  selector:
    app: influxdb
